config/routes.rb
DemoBrander::Application.routes.draw do

  resources :users
  resources :leads

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  include Databasedotcom::Rails::Controller

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    # ADD ME
    @lead['OwnerId'] = '00530000008Tqzr'
    @lead['IsConverted'] = false
    @lead['IsUnreadByOwner'] = true
    # END

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include Databasedotcom::Rails::Controller

	def index
		@users = User.query("Id != NULL ORDER BY Id LIMIT 20")
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params[:user])
		render "show"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoBrander</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FirstName %><br />
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br />
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Company %><br />
    <%= f.text_field :Company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Listing leads</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads.each do |lead| %>
  <tr>
    <td><%= lead.FirstName %></td>
    <td><%= lead.LastName %></td>
    <td><%= lead.Company %></td>
    <td><%= link_to 'Show', lead_path(lead) %></td>
    <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
    <td><%= link_to 'Destroy', lead_path(lead), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @lead.FirstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @lead.LastName %>
</p>

<p>
  <b>Company:</b>
  <%= @lead.Company %>
</p>


<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/users/edit.html.erb
<h1>Editing user  <%= @user.Name %> </h1>

<%= form_for(@user) do |f| %>
    <div class="field">
        <%= f.label :CompanyName %><br />
        <%= f.text_field :CompanyName %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <%= link_to "#{user.Name}", "/users/#{user.Id}" %><br/>
<% end %>

app/views/users/show.html.erb
<h1>User <%= @user.Name %></h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<br/>
<br/>

<% @user.attributes.each do |a| %>
    <%= a[0] %>: <%= a[1] %><br/>
<% end %>